/*
 * api
 *
 * <br/>https://sourcecommit.apigw.ntruss.com/api/v1
 *
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package sourcecommit

type GetRepositoryListResponse struct {
	Result *GetRepositoryListResponseResult `json:"result"`
}
